// <auto-generated />
using System;
using InverumHub.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InverumHub.DataLayer.Migrations
{
    [DbContext(typeof(InverumDbContext))]
    [Migration("20260108182030_UpdateSeed")]
    partial class UpdateSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("InverumHub.Core.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("applications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "ssot",
                            Description = "Enities Manager",
                            IsActive = true,
                            Name = "Identity SSOT"
                        },
                        new
                        {
                            Id = 2001,
                            Alias = "customer_web_app",
                            Description = "Front end portal for customers",
                            IsActive = true,
                            Name = "Customer Portal Web"
                        },
                        new
                        {
                            Id = 2002,
                            Alias = "admin_dashboard",
                            Description = "Admin Backoffice",
                            IsActive = true,
                            Name = "Admin Backoffice"
                        },
                        new
                        {
                            Id = 2003,
                            Alias = "mobile_app",
                            Description = "Android/iOS application",
                            IsActive = true,
                            Name = "Mobile App"
                        });
                });

            modelBuilder.Entity("InverumHub.Core.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "USER_READ",
                            Description = "Read users"
                        },
                        new
                        {
                            Id = 2,
                            Code = "USER_WRITE",
                            Description = "Write users"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ROLE_READ",
                            Description = "Read roles"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ROLE_WRITE",
                            Description = "Write roles"
                        });
                });

            modelBuilder.Entity("InverumHub.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full access to all system features and settings.",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Standard user with limited access to features.",
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Read-only access to public information.",
                            Name = "Guest"
                        },
                        new
                        {
                            Id = 999,
                            Description = "Root Admin",
                            Name = "SSOT_ADMIN"
                        });
                });

            modelBuilder.Entity("InverumHub.Core.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        });
                });

            modelBuilder.Entity("InverumHub.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InverumHub.Core.Entities.UserApplicationRole", b =>
                {
                    b.Property<Guid>("UserUid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserUid", "ApplicationId", "RoleId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_application_roles", (string)null);
                });

            modelBuilder.Entity("InverumHub.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("InverumHub.Core.Entities.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InverumHub.Core.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InverumHub.Core.Entities.UserApplicationRole", b =>
                {
                    b.HasOne("InverumHub.Core.Entities.Application", "Application")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InverumHub.Core.Entities.Role", "Role")
                        .WithMany("UserApplication")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InverumHub.Core.Entities.User", "User")
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InverumHub.Core.Entities.Application", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("InverumHub.Core.Entities.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("InverumHub.Core.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserApplication");
                });

            modelBuilder.Entity("InverumHub.Core.Entities.User", b =>
                {
                    b.Navigation("ApplicationRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
